# fly.toml app configuration file generated for indie-visible-dev on 2023-08-13T13:54:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "indie-visible-staging"
primary_region = "ewr"
console_command = "/rails/bin/rails console"

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/root/work/public"
  url_prefix = "/"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"
