# fly.toml app configuration file generated for bbc-hub-dev on 2023-07-29T20:47:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "indie-visible-staging"
primary_region = "ewr"
console_command = "/rails/bin/rails console"

[processes]
  app = "./bin/rails server"

[http_service]
  processes = ['app'] # this service only applies to the app process
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/root/work/public"
  url_prefix = "/"
